[package]
name = "rsconf"
version = "0.1.0"
edition = "2021"

[dependencies]
cc = { git = "https://github.com/mqudsi/cc-rs.git", branch = "master" }
tempfile = "3.0"

[dev-dependencies]
once_cell = "1.17.1"
